import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Card } from '@/components/ui/card';
import { CheckCircle, AlertTriangle, Target, Brain } from 'lucide-react';

export default function AIInsights({ insights }) {
  if (!insights) return null;

  return (
    <Card className="p-6 bg-gradient-to-br from-blue-50 to-purple-50 border-blue-200">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 rounded-full bg-gradient-to-br from-blue-600 to-purple-600 flex items-center justify-center">
          <Brain className="h-6 w-6 text-white" />
        </div>
        <div>
          <h3 className="text-xl font-bold text-slate-900">Your AI Trading Analysis</h3>
          <p className="text-sm text-slate-600">Generated by advanced analysis</p>
        </div>
      </div>

      <div className="prose prose-sm max-w-none">
        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h2 className="text-2xl font-bold text-slate-900 mt-6 mb-3 flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-green-600" />
                {children}
              </h2>
            ),
            h2: ({ children }) => {
              const text = String(children);
              let Icon = Target;
              let color = 'text-blue-600';
              
              if (text.toLowerCase().includes('strength')) {
                Icon = CheckCircle;
                color = 'text-green-600';
              } else if (text.toLowerCase().includes('improvement') || text.toLowerCase().includes('weakness')) {
                Icon = AlertTriangle;
                color = 'text-orange-600';
              } else if (text.toLowerCase().includes('recommendation')) {
                Icon = Target;
                color = 'text-purple-600';
              }
              
              return (
                <h3 className={`text-lg font-bold ${color} mt-4 mb-2 flex items-center gap-2`}>
                  <Icon className="h-4 w-4" />
                  {children}
                </h3>
              );
            },
            h3: ({ children }) => (
              <h4 className="text-base font-semibold text-slate-800 mt-3 mb-2">{children}</h4>
            ),
            ul: ({ children }) => (
              <ul className="space-y-2 my-3">{children}</ul>
            ),
            li: ({ children }) => (
              <li className="flex items-start gap-2 text-slate-700">
                <span className="text-blue-600 mt-1">•</span>
                <span>{children}</span>
              </li>
            ),
            p: ({ children }) => (
              <p className="text-slate-700 my-2 leading-relaxed">{children}</p>
            ),
            strong: ({ children }) => (
              <strong className="font-semibold text-slate-900">{children}</strong>
            ),
            em: ({ children }) => (
              <em className="italic text-slate-600">{children}</em>
            ),
            code: ({ children }) => (
              <code className="bg-white px-2 py-0.5 rounded text-sm text-blue-700 border border-blue-200">
                {children}
              </code>
            ),
            blockquote: ({ children }) => (
              <blockquote className="border-l-4 border-blue-500 pl-4 py-2 my-3 bg-white/50 rounded-r">
                {children}
              </blockquote>
            )
          }}
        >
          {insights}
        </ReactMarkdown>
      </div>

      <div className="mt-6 pt-6 border-t border-blue-200">
        <p className="text-xs text-slate-500 italic">
          💡 These insights are AI-generated based on your trading data. Always verify recommendations with your own analysis.
        </p>
      </div>
    </Card>
  );
}